import {
  FileText,
  Wallet,
  Gauge,
  HandCoins,
  Scale,
  BellRing,
  Megaphone,
  PhoneCall,
  Landmark,
  Building2,
  RadioTower,
  Sparkles,
  // Capability icons (solution detail pages)
  Smartphone,
  ShieldCheck,
  ScanLine,
  SlidersHorizontal,
  Workflow,
  FileSignature,
  Banknote,
  CalendarClock,
  Percent,
  Layers,
  BookOpen,
  Database,
  Signal,
  Activity,
  Lightbulb,
  FlaskConical,
  Zap,
  Users,
  Target,
  MessagesSquare,
  CalendarCheck,
  Headset,
  LayoutDashboard,
  GitCompareArrows,
  TriangleAlert,
  Timer,
  FolderInput,
  FileCheck,
  Clock,
  Wand2,
  TrendingUp,
  Route,
  Send,
  BarChart3,
  // Product category icons
  Repeat,
  Wifi,
  CreditCard,
  HeartPulse,
  Truck,
  Handshake,
  Boxes,
  Briefcase,
  type LucideIcon,
} from "lucide-react";

/** Registry of icons referenced by string name in the content/data layer. */
const ICONS: Record<string, LucideIcon> = {
  FileText,
  Wallet,
  Gauge,
  HandCoins,
  Scale,
  BellRing,
  Megaphone,
  PhoneCall,
  Landmark,
  Building2,
  RadioTower,
  Sparkles,
  Smartphone,
  ShieldCheck,
  ScanLine,
  SlidersHorizontal,
  Workflow,
  FileSignature,
  Banknote,
  CalendarClock,
  Percent,
  Layers,
  BookOpen,
  Database,
  Signal,
  Activity,
  Lightbulb,
  FlaskConical,
  Zap,
  Users,
  Target,
  MessagesSquare,
  CalendarCheck,
  Headset,
  LayoutDashboard,
  GitCompareArrows,
  TriangleAlert,
  Timer,
  FolderInput,
  FileCheck,
  Clock,
  Wand2,
  TrendingUp,
  Route,
  Send,
  BarChart3,
  Repeat,
  Wifi,
  CreditCard,
  HeartPulse,
  Truck,
  Handshake,
  Boxes,
  Briefcase,
};

/** Resolve a Lucide icon by name, falling back to Sparkles if unknown. */
export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Sparkles;
}
